apiVersion: 1

datasources:
  - name: pg_dwh
    uid: pg_dwh
    type: postgres
    access: proxy
    isDefault: true
    editable: true
    url: pg_dwh:5432
    user: ${PG_DWH_USER}
    secureJsonData:
      password: ${PG_DWH_PASSWORD}
    jsonData:
      database: ${PG_DWH_DB}
      sslmode: disable
      postgresVersion: 1600
      timescaledb: true
